# 模糊抓取订阅链接
# - type: webfuzzsub
#   options:
#     # url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe # for ps field int type test
  options:
    url: https://raw.githubusercontent.com/ntkernel/lantern/master/vmess_base64.txt
- type: subscribe # for ps field int type test
  options:
    url: https://www.qsc.zju.edu.cn/box/-vmess

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# 某个网站抓取
- type: web-freessrxyz # for adding an extra character at index 15 per line
  options:
